---
# # For Debian/Ubuntu
# wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
# sudo apt-get install ./cloudflared-linux-amd64.deb
# cloudflared -v

- name: Download cloudflared
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm
    dest: /tmp/cloudflared-linux-x86_64.rpm
