---
- import_tasks: debian.yml
  when: 
    - ansible_distribution == 'Debian'

- import_tasks: redhat.yml
  when: 
    - ansible_facts['os_family'] == "RedHat"

- name: Check if cloudflared is installed
  ansible.builtin.shell: |
    cloudflared -v
  changed_when: false
  register: cloudflared_status
  ignore_errors: true

- name: Print cloudflared status
  ansible.builtin.debug:
    var: cloudflared_status

- name: Create a cloudflared user to run the daemon
  ansible.builtin.user:
    name: cloudflared
    shell: /usr/sbin/nologin
    create_home: false
    system: true
    state: present

- name: create a configuration file for cloudflared
  become: true
  ansible.builtin.template:
    src: cloudflared.j2
    dest: /etc/default/cloudflared

- name: Change file ownership and group for cloudflared configuration file
  ansible.builtin.file:
    path: /etc/default/cloudflared
    owner: cloudflared
    group: cloudflared

- name: Change file ownership and group for cloudflared executable file
  ansible.builtin.file:
    path: /usr/local/bin/cloudflared
    owner: cloudflared
    group: cloudflared

- name: create the cloudflared systemd script
  become: true
  ansible.builtin.template:
    src: cloudflared.service.j2
    dest: /etc/systemd/system/cloudflared.service
    mode: "0644"

- name: enable and start cloudflared
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: cloudflared
    enabled: yes
    masked: no