---
# For CentOS/RHEL/Fedora
- name: Download cloudflared
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm
    dest: /tmp/cloudflared-linux-x86_64.rpm

- name: Install cloudflared rpm from a local file
  ansible.builtin.yum:
    name: /tmp/cloudflared-linux-x86_64.rpm
    disable_gpg_check: true
    state: present

