---
- name: create ip_nonlocal_bind configuration
  ansible.builtin.copy:
    src: "ip_nonlocal_bind.conf"
    dest: "/etc/sysctl.d/ip_nonlocal_bind.conf"
  notify: reload sysctl config

- name: flush handlers
  meta: flush_handlers

- name: update packages cache
  ansible.builtin.dnf:
    update_cache: true
    state: latest

- name: ensure a list of RPM packages are installed
  ansible.builtin.dnf:
    name: "{{ pkgs_add_rpm }}"
    state: present
  vars:
    pkgs_add_rpm:
      - keepalived

# # - name: Copy check_pihole.sh
# #   copy:
# #     dest: /etc/keepalived/check_pihole.sh
# #     src: check_pihole.sh
# #     mode: 0755

# - name: Configure keepalived
#   template:
#     dest: /etc/keepalived/keepalived.conf
#     src: keepalived.j2
#     mode: 0644
#   notify: Restart keepalived service

# - name: Flush handlers
#   meta: flush_handlers


# #systemctl enable --now keepalived.service
# #systemctl status keepalived.service