---
- name: "stop and disable suspend/hibernation"
  ansible.builtin.systemd:
    state: stopped
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
    masked: yes
  loop: 
    - sleep
    - suspend
    - hibernate
    - hybrid-sleep

- name: "update logind configuration"
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#HandleLidSwitch=suspend"
    line: "    state BACKUP"
  loop: 
    - { regexp: '^#HandleLidSwitch=suspend', line: 'HandleLidSwitch=ignore' }
    - { regexp: '#HandleLidSwitchExternalPower=suspend', line: 'HandleLidSwitchExternalPower=ignore' }
    - { regexp: '#HandleLidSwitchDocked=ignore', line: 'HandleLidSwitchDocked=ignore' }

- name: Reboot Server
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami