---
- name: create/update ssh banner
  become: true
  ansible.builtin.template:
    src: ssh-banner.j2
    dest: /etc/issue.net
  notify:
    - restart sshd

- name: update ssh settings
  become: true
  ansible.builtin.template:
    src: 60-local.conf.j2
    dest: /etc/ssh/sshd_config.d/60-local.conf
  notify:
    - restart sshd