---
- import_tasks: debian.yml
  when: 
    - ansible_distribution == 'Debian'

- import_tasks: redhat.yml
  when: 
    - ansible_facts['os_family'] == "RedHat"

- name: Set authorized key for user
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ item }}"
    validate_certs: "no"
  loop: "{{ github_ssh_key_url }}"
  when: github_ssh_key_url != None

- name: Print ansible user
  ansible.builtin.debug:
    msg: "{{ ansible_env.SUDO_USER }}"

- name: Pause to get a new user password
  ansible.builtin.pause:
    prompt: "Enter a new user password"
    echo: no
  register: new_password
  when: change_password | bool

- set_fact:
    new_password: "{{ new_password.user_input | password_hash('sha512') }}"
  when: change_password | bool   

# Change password
- name: Change user password
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER }}"
    update_password: always
    password: "{{ new_password }}"
  when: change_password | bool