---
- name: Remove 'wheel' group password sudo configuration
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel  ALL=(ALL)       ALL'
    line: '# %wheel  ALL=(ALL)       ALL'
    validate: 'visudo -cf %s'

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^# %wheel        ALL=(ALL)       NOPASSWD: ALL'
    line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
    validate: 'visudo -cf %s'
