---
- name: Setting a hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}.{{ domain }}"

- name: Fixing hosts file
  lineinfile:
    path: /etc/hosts
    search_string: '127.0.1.1'
    line: "127.0.1.1 {{ hostname }}.{{ domain }} {{ hostname }}"