- name: restart sshd
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: sshd

# does not seem to work with azure vm
- name: reboot
  become: true
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
