---
- name: restart pihole
  ansible.builtin.shell: pihole restartdns

- name: restart pihole DNS resolver
  ansible.builtin.systemd:
    name: pihole-FTL.service
    state: restarted
  listen: restart pihole-FTL