---
- name: Make sure we have a 'sudo' group
  group:
    name: sudo
    state: present

- name: Add the user admin with a bash shell, appending the group 'sudo'
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Set authorized key for user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ item }}"
    validate_certs: "no"
  loop: "{{ github_ssh_key_url }}"
  when: github_ssh_key_url != None

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: ansible_user == "root"

# - name: Add user to wheel group
#   user:
#     name: "{{username}}"
#     groups:
#       - wheel
#     append: yes
#     state: present
#     createhome: yes
#     shell: /bin/bash
#   when: ansible_user == "root"

- name: Print ansible user
  debug:
    msg: "{{ ansible_env.SUDO_USER }}"

- name: Pause to get a new dadmin password
  ansible.builtin.pause:
    prompt: "Enter a new dadmin password"
    echo: no
  register: new_password
  when: change_password | bool

- set_fact:
    new_password: "{{ new_password.user_input | password_hash('sha512') }}"
  when: change_password | bool   

# Change password
- name: Change dadmin password
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    update_password: always
    password: "{{ new_password }}"
  when: change_password | bool